In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("/content/Student_Performance.csv")

In [ ]:
df

,student_id,age,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,math_score,science_score,english_score,overall_score,final_grade
0,1,14,male,public,post graduate,3.1,84.3,yes,<15 min,yes,notes,42.7,55.4,57.0,53.1,e
1,2,18,female,public,graduate,3.7,87.8,yes,>60 min,no,textbook,57.6,68.8,64.8,61.3,d
2,3,17,female,private,post graduate,7.9,65.5,no,<15 min,no,notes,84.8,95.0,79.2,89.6,b
3,4,16,other,public,high school,1.1,58.1,no,15-30 min,no,notes,44.4,27.5,54.7,41.6,e
4,5,16,female,public,high school,1.3,61.0,yes,30-60 min,yes,group study,8.9,32.7,30.0,25.4,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,12047,17,female,public,phd,1.8,55.2,yes,15-30 min,no,mixed,55.8,48.5,46.7,46.1,e
24996,1102,16,female,private,diploma,2.7,97.1,yes,<15 min,no,coaching,64.8,48.2,52.3,56.5,d
24997,4422,19,other,private,post graduate,1.0,63.0,yes,<15 min,no,group study,50.5,20.3,36.1,36.7,f
24998,7858,14,male,private,diploma,1.0,69.4,yes,15-30 min,yes,group study,13.0,34.2,7.3,34.1,f
24999,11621,18,other,public,no formal,0.7,60.3,yes,30-60 min,no,mixed,36.5,45.1,16.5,31.4,f

In [4]:
pd.value_counts(df['final_grade'])

/tmp/ipykernel_8400/3307304445.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(df['final_grade'])

final_grade
d    6311
c    6161
e    5672
f    2955
b    2696
a    1205
Name: count, dtype: int64

In [ ]:
print(f'column: {"gender"}, categories: {df["gender"].unique()}')

column: gender, categories: ['male' 'female' 'other']

In [ ]:
print(f'column: {"school_type"}, \n categories: {df["school_type"].unique()}')

column: school_type,
 categories: ['public' 'private']

In [ ]:
print(f'column: {"parent_education"}, \n categories: {df["parent_education"].unique()}')

column: parent_education,
 categories: ['post graduate' 'graduate' 'high school' 'no formal' 'diploma' 'phd']

In [5]:
from sklearn.preprocessing import OrdinalEncoder

# Define nominal and ordinal categorical columns
nominal_cols = ['gender', 'school_type', 'internet_access', 'extra_activities', 'study_method']
ordinal_cols = ['parent_education', 'travel_time'] # Removed 'final_grade'

# Create a copy to avoid modifying the original DataFrame directly
df_encoded = df.copy()

### Ordinal Encoding for `parent_education`, `travel_time`, and `final_grade`

In [6]:
# Define the order for ordinal categories
parent_education_order = ['no formal', 'diploma', 'high school', 'graduate', 'post graduate', 'phd']
travel_time_order = ['<15 min', '15-30 min', '30-60 min', '>60 min']
# final_grade_order = ['a', 'b', 'c', 'd', 'e', 'f'] # Removed final_grade order as it's not being encoded

# Initialize and apply OrdinalEncoder
encoder_parent_education = OrdinalEncoder(categories=[parent_education_order])
df_encoded['parent_education_encoded'] = encoder_parent_education.fit_transform(df_encoded[['parent_education']])

encoder_travel_time = OrdinalEncoder(categories=[travel_time_order])
df_encoded['travel_time_encoded'] = encoder_travel_time.fit_transform(df_encoded[['travel_time']])

# Removed final_grade encoding
# encoder_final_grade = OrdinalEncoder(categories=[final_grade_order])
# df_encoded['final_grade_encoded'] = encoder_final_grade.fit_transform(df_encoded[['final_grade']])

### One-Hot Encoding for Nominal Features

In [7]:
# Apply one-hot encoding using pd.get_dummies
df_encoded = pd.get_dummies(df_encoded, columns=nominal_cols, drop_first=True)

# Drop the original categorical columns
df_encoded = df_encoded.drop(columns=ordinal_cols)

# Display the first few rows of the encoded DataFrame
display(df_encoded.head())

,student_id,age,study_hours,attendance_percentage,math_score,science_score,english_score,overall_score,final_grade,parent_education_encoded,...,gender_male,gender_other,school_type_public,internet_access_yes,extra_activities_yes,study_method_group study,study_method_mixed,study_method_notes,study_method_online videos,study_method_textbook
0,1,14,3.1,84.3,42.7,55.4,57.0,53.1,e,4.0,...,True,False,True,True,True,False,False,True,False,False
1,2,18,3.7,87.8,57.6,68.8,64.8,61.3,d,3.0,...,False,False,True,True,False,False,False,False,False,True
2,3,17,7.9,65.5,84.8,95.0,79.2,89.6,b,4.0,...,False,False,False,False,False,False,False,True,False,False
3,4,16,1.1,58.1,44.4,27.5,54.7,41.6,e,2.0,...,False,True,True,False,False,False,False,True,False,False
4,5,16,1.3,61.0,8.9,32.7,30.0,25.4,f,2.0,...,False,False,True,True,True,True,False,False,False,False

In [8]:
# Identify boolean columns
boolean_cols = df_encoded.select_dtypes(include='bool').columns

# Convert boolean columns to int (0s and 1s)
df_encoded[boolean_cols] = df_encoded[boolean_cols].astype(int)

display(df_encoded.head())

,student_id,age,study_hours,attendance_percentage,math_score,science_score,english_score,overall_score,final_grade,parent_education_encoded,...,gender_male,gender_other,school_type_public,internet_access_yes,extra_activities_yes,study_method_group study,study_method_mixed,study_method_notes,study_method_online videos,study_method_textbook
0,1,14,3.1,84.3,42.7,55.4,57.0,53.1,e,4.0,...,1,0,1,1,1,0,0,1,0,0
1,2,18,3.7,87.8,57.6,68.8,64.8,61.3,d,3.0,...,0,0,1,1,0,0,0,0,0,1
2,3,17,7.9,65.5,84.8,95.0,79.2,89.6,b,4.0,...,0,0,0,0,0,0,0,1,0,0
3,4,16,1.1,58.1,44.4,27.5,54.7,41.6,e,2.0,...,0,1,1,0,0,0,0,1,0,0
4,5,16,1.3,61.0,8.9,32.7,30.0,25.4,f,2.0,...,0,0,1,1,1,1,0,0,0,0

In [9]:
from sklearn.model_selection import train_test_split

# Define features (X) and target (y)
# 'final_grade' is now the target, so 'overall_score' should be in features and 'final_grade' should be dropped from features
X = df_encoded.drop(columns=['student_id', 'final_grade'])
y = df_encoded['final_grade']

# Perform train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

X_train shape: (20000, 19)
X_test shape: (5000, 19)
y_train shape: (20000,)
y_test shape: (5000,)

### Addressing Data Leakage: Removing `overall_score`

The `overall_score` column is highly correlated with (and likely directly determines) the `final_grade`. Including it as a feature would lead to data leakage, where the model essentially 'sees' the answer during training, resulting in unrealistically high performance metrics. To build a robust model that learns from independent features, we must remove `overall_score` from our feature set `X`.

In [10]:
import pandas as pd

# Remove 'overall_score' from features in X_train and X_test to prevent data leakage
# Check if 'overall_score' exists before dropping to prevent KeyError if run multiple times
if 'overall_score' in X_train.columns:
    X_train = X_train.drop(columns=['overall_score'])
if 'overall_score' in X_test.columns:
    X_test = X_test.drop(columns=['overall_score'])

print(f"X_train shape after removing overall_score: {X_train.shape}")
print(f"X_test shape after removing overall_score: {X_test.shape}")

X_train shape after removing overall_score: (20000, 18)
X_test shape after removing overall_score: (5000, 18)

In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [13]:
import joblib
joblib.dump(scaler, 'scaler.joblib')
print("Scaler saved successfully as 'scaler.joblib'")

Scaler saved successfully as 'scaler.joblib'

In [14]:
from sklearn.linear_model import LogisticRegression

In [ ]:
X_train_scaled

array([[-1.46020841,  1.12709585, -1.11412593, ..., -0.44396285,
         2.23862049, -0.45224886],
       [ 1.47700929, -1.45644678, -1.3302302 , ..., -0.44396285,
        -0.44670367, -0.45224886],
       [-1.46020841,  0.25053674,  1.02600349, ..., -0.44396285,
         2.23862049, -0.45224886],
       ...,
       [ 1.47700929, -1.59485085,  1.61854746, ..., -0.44396285,
        -0.44670367, -0.45224886],
       [-0.28532133,  1.26549992, -1.00258824, ..., -0.44396285,
        -0.44670367,  2.21117198],
       [-1.46020841,  0.25053674, -1.02350156, ..., -0.44396285,
        -0.44670367,  2.21117198]])

In [ ]:
lr = LogisticRegression(max_iter=2000)
model = lr.fit(X_train_scaled, y_train)

In [ ]:
y_pred = model.predict(X_test_scaled)

In [ ]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [ ]:
Report = classification_report(y_test, y_pred)

In [ ]:
Acc_score = accuracy_score(y_test, y_pred)

In [ ]:
print(f'Classification Report: \n {Report}')
print(f'Accuracy Score: {Acc_score}')

Classification Report:
               precision    recall  f1-score   support

           a       0.74      0.71      0.72       256
           b       0.67      0.63      0.65       542
           c       0.77      0.80      0.78      1198
           d       0.77      0.76      0.77      1268
           e       0.78      0.80      0.79      1152
           f       0.85      0.80      0.82       584

    accuracy                           0.77      5000
   macro avg       0.76      0.75      0.76      5000
weighted avg       0.77      0.77      0.77      5000

Accuracy Score: 0.7686

In [ ]:
C_matrix = confusion_matrix(y_test, y_pred)
print(C_matrix)

[[181  75   0   0   0   0]
 [ 62 342 138   0   0   0]
 [  2  94 959 143   0   0]
 [  0   0 156 969 143   0]
 [  0   0   0 144 922  86]
 [  0   0   0   0 114 470]]

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [ ]:
knn = KNeighborsClassifier(n_neighbors=5)
k_model = knn.fit(X_train_scaled, y_train)

In [ ]:
y_pred_2 = k_model.predict(X_test_scaled)

In [ ]:
Knn_report = classification_report(y_test, y_pred_2)

In [ ]:
knn_accuracy_score = accuracy_score(y_test, y_pred_2)

In [ ]:
print(f'Classification Report: {Knn_report}')
print(f'Accuracy Score: {knn_accuracy_score}')

Classification Report:               precision    recall  f1-score   support

           a       0.53      0.49      0.51       256
           b       0.52      0.54      0.53       542
           c       0.65      0.70      0.67      1198
           d       0.66      0.67      0.66      1268
           e       0.69      0.71      0.70      1152
           f       0.80      0.63      0.70       584

    accuracy                           0.66      5000
   macro avg       0.64      0.62      0.63      5000
weighted avg       0.66      0.66      0.66      5000

Accuracy Score: 0.6554

In [ ]:
Rf = RandomForestClassifier()
R_forest_model = Rf.fit(X_train_scaled, y_train)

In [ ]:
y_pred_rf = R_forest_model.predict(X_test_scaled)
Rf_accuracy = accuracy_score(y_test, y_pred_rf)

In [ ]:
print(f'Accuracy score: {Rf_accuracy}')

Accuracy score: 0.8782

In [ ]:
Rf_class_report = classification_report(y_test, y_pred_rf)
print(f'RF Classification report: \n {Rf_class_report}')

RF Classification report:
               precision    recall  f1-score   support

           a       0.91      0.83      0.87       256
           b       0.82      0.82      0.82       542
           c       0.88      0.90      0.89      1198
           d       0.88      0.88      0.88      1268
           e       0.88      0.89      0.88      1152
           f       0.92      0.88      0.90       584

    accuracy                           0.88      5000
   macro avg       0.88      0.87      0.87      5000
weighted avg       0.88      0.88      0.88      5000

In [ ]:
svc = SVC()
svc_model = svc.fit(X_train_scaled, y_train)

In [ ]:
svc_pred = svc_model.predict(X_test_scaled)
svc_class_report = classification_report(y_test, svc_pred)

In [ ]:
print(svc_class_report)

              precision    recall  f1-score   support

           a       0.77      0.68      0.72       256
           b       0.69      0.67      0.68       542
           c       0.78      0.81      0.79      1198
           d       0.78      0.77      0.78      1268
           e       0.79      0.82      0.81      1152
           f       0.87      0.82      0.84       584

    accuracy                           0.78      5000
   macro avg       0.78      0.76      0.77      5000
weighted avg       0.78      0.78      0.78      5000

In [ ]:
print(accuracy_score(y_test, svc_pred))

0.7822

### Cross-Validation with Random Forest

To find the best hyperparameters for the Random Forest model and ensure its robustness, we will perform cross-validation using `GridSearchCV`. This method systematically works through multiple combinations of parameter tunes, cross-validating each combination to determine which produces the best performance.

In [ ]:
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.ensemble import RandomForestClassifier

# Define the parameter grid to search
param_grid = {
    'n_estimators': [100, 200, 300], # Number of trees in the forest
    'max_features': ['sqrt', 'log2'], # Number of features to consider when looking for the best split
    'max_depth': [10, 20, None], # Maximum depth of the tree
    'min_samples_leaf': [1, 2, 4] # Minimum number of samples required to be at a leaf node
}

# Initialize the Random Forest Classifier
rf_cv = RandomForestClassifier(random_state=42)

# Set up StratifiedKFold for cross-validation to maintain class distribution
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Initialize GridSearchCV
grid_search = GridSearchCV(estimator=rf_cv, param_grid=param_grid,
                           cv=skf, n_jobs=-1, verbose=2, scoring='accuracy')

# Fit GridSearchCV to the training data
grid_search.fit(X_train_scaled, y_train)

# Print the best parameters and best score
print(f"Best parameters found: {grid_search.best_params_}")
print(f"Best cross-validation accuracy: {grid_search.best_score_:.4f}")

Fitting 5 folds for each of 54 candidates, totalling 270 fits

KeyboardInterrupt:

**RANDOM FOREST WITH THE BEST PARAMETERS**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

# Initialize RandomForestClassifier with the best parameters
best_rf_explicit = RandomForestClassifier(
    n_estimators=100,
    max_features='sqrt',
    max_depth=20,
    min_samples_leaf=1,
    random_state=42 # Ensure reproducibility
)

# Train the model
best_rf_explicit.fit(X_train_scaled, y_train)

# Make predictions on the test set
y_pred_explicit_rf = best_rf_explicit.predict(X_test_scaled)

# Evaluate the model
explicit_rf_accuracy = accuracy_score(y_test, y_pred_explicit_rf)
explicit_rf_report = classification_report(y_test, y_pred_explicit_rf)

print(f"Explicit Random Forest Model Test Accuracy: {explicit_rf_accuracy:.4f}")
print(f"\nExplicit Random Forest Model Classification Report:\n{explicit_rf_report}")

Explicit Random Forest Model Test Accuracy: 0.8800

Explicit Random Forest Model Classification Report:
              precision    recall  f1-score   support

           a       0.90      0.82      0.85       256
           b       0.82      0.82      0.82       542
           c       0.88      0.90      0.89      1198
           d       0.88      0.88      0.88      1268
           e       0.89      0.90      0.89      1152
           f       0.92      0.89      0.91       584

    accuracy                           0.88      5000
   macro avg       0.88      0.87      0.87      5000
weighted avg       0.88      0.88      0.88      5000

### Evaluate the Best Random Forest Model

Now that we have found the best hyperparameters using cross-validation, we will evaluate this best model on the unseen test set to get a final performance estimate.

In [ ]:
from sklearn.metrics import classification_report, accuracy_score

# Get the best model from GridSearchCV
best_rf_model = best_rf_explicit

# Make predictions on the test set
y_pred_best_rf = best_rf_model.predict(X_test_scaled)

# Evaluate the best model
best_rf_accuracy = accuracy_score(y_test, y_pred_best_rf)
best_rf_report = classification_report(y_test, y_pred_best_rf)

print(f"Best Random Forest Model Test Accuracy: {best_rf_accuracy:.4f}")
print(f"\nBest Random Forest Model Classification Report:\n{best_rf_report}")

Best Random Forest Model Test Accuracy: 0.8800

Best Random Forest Model Classification Report:
              precision    recall  f1-score   support

           a       0.90      0.82      0.85       256
           b       0.82      0.82      0.82       542
           c       0.88      0.90      0.89      1198
           d       0.88      0.88      0.88      1268
           e       0.89      0.90      0.89      1152
           f       0.92      0.89      0.91       584

    accuracy                           0.88      5000
   macro avg       0.88      0.87      0.87      5000
weighted avg       0.88      0.88      0.88      5000

### Save the Best Random Forest Model

It's good practice to save trained models so they can be re-used without needing to retrain them. We'll use `joblib` for this purpose, which is efficient for large NumPy arrays and objects with C extensions, commonly used in scikit-learn.

In [ ]:
import joblib

# Define the filename for the saved model
model_filename = 'best_random_forest_model.joblib'

# Save the best model
joblib.dump(best_rf_model, model_filename)

print(f"Best Random Forest model saved successfully as '{model_filename}'")

Best Random Forest model saved successfully as 'best_random_forest_model.joblib'

### Running Random Forest with Best Parameters

Based on the cross-validation results, we will now explicitly initialize and train a `RandomForestClassifier` using the optimal hyperparameters found: `max_depth=20`, `max_features='sqrt'`, `min_samples_leaf=1`, and `n_estimators=100`. We will then evaluate its performance on the test set.

In [ ]:
import joblib

In [ ]:
model_rf = joblib.load("/content/best_random_forest_model.joblib")

In [ ]:
# Load the scaler object
scaler = joblib.load('scaler.joblib')
print("Scaler loaded successfully.")

FileNotFoundError: [Errno 2] No such file or directory: 'scaler.joblib'

In [ ]:
# Define train_columns simulating a production environment where X_train is not available.
# These columns represent the features used for training after all preprocessing steps.
# We derive them from df_encoded by dropping the 'student_id', 'final_grade', and 'overall_score' columns.
production_train_columns = df_encoded.drop(columns=['student_id', 'final_grade', 'overall_score']).columns.tolist()
print("Production training columns defined.")

Production training columns defined.

In [ ]:
df.columns

Index(['student_id', 'age', 'gender', 'school_type', 'parent_education',
       'study_hours', 'attendance_percentage', 'internet_access',
       'travel_time', 'extra_activities', 'study_method', 'math_score',
       'science_score', 'english_score', 'overall_score', 'final_grade'],
      dtype='object')

In [ ]:
columns = ['student_id', 'age', 'gender', 'school_type', 'parent_education',
       'study_hours', 'attendance_percentage', 'internet_access',
       'travel_time', 'extra_activities', 'study_method', 'math_score',
       'science_score', 'english_score', 'overall_score', 'final_grade']
input_df = pd.DataFrame(columns=columns)

In [ ]:
input_df.loc[0] = [1, 18, 'male', 'private', 'phd', '7']

Empty DataFrame
Columns: [student_id, age, gender, school_type, parent_education, study_hours, attendance_percentage, internet_access, travel_time, extra_activities, study_method, math_score, science_score, english_score, overall_score, final_grade]
Index: []

In [ ]:
import random

sample_input_data = {
    'student_id': random.randint(100000, 999999), # Generate a random student_id
    'age': 18,
    'gender': 'male',
    'school_type': 'private',
    'parent_education': 'phd',
    'study_hours': 7.0,
    'attendance_percentage': 90.0,
    'internet_access': 'yes',
    'travel_time': '<15 min',
    'extra_activities': 'yes',
    'study_method': 'notes',
    'math_score': 85.0,
    'science_score': 92.0,
    'english_score': 88.0
}

input_df_raw = pd.DataFrame([sample_input_data])

display(input_df_raw)

,student_id,age,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,math_score,science_score,english_score
0,267068,18,male,private,phd,7.0,90.0,yes,<15 min,yes,notes,85.0,92.0,88.0

Now, let's apply the same preprocessing steps to this single input row as we did for the training data.

In [ ]:
# Make a copy to apply transformations
input_df_processed = input_df_raw.copy()

# Ordinal Encoding
input_df_processed['parent_education_encoded'] = encoder_parent_education.transform(input_df_processed[['parent_education']])
input_df_processed['travel_time_encoded'] = encoder_travel_time.transform(input_df_processed[['travel_time']])

# One-Hot Encoding
# Need to create dummy variables for nominal_cols present in the input_df_processed
input_df_processed = pd.get_dummies(input_df_processed, columns=nominal_cols, drop_first=True)

# Drop original categorical columns and 'student_id', 'overall_score', 'final_grade'
columns_to_drop = ordinal_cols + nominal_cols + ['student_id', 'overall_score', 'final_grade']
input_df_processed = input_df_processed.drop(columns=columns_to_drop, errors='ignore')

# Convert boolean columns to int
boolean_cols_input = input_df_processed.select_dtypes(include='bool').columns
input_df_processed[boolean_cols_input] = input_df_processed[boolean_cols_input].astype(int)

# Align columns with X_train - this is critical!
# Get the columns from the training data (X_train) after dropping 'overall_score'
train_columns = X_train.columns

# Reindex the input DataFrame to match the training columns
# Add missing columns with 0 and drop extra ones
input_df_processed = input_df_processed.reindex(columns=train_columns, fill_value=0)


display(input_df_processed)

,age,study_hours,attendance_percentage,math_score,science_score,english_score,parent_education_encoded,travel_time_encoded,gender_male,gender_other,school_type_public,internet_access_yes,extra_activities_yes,study_method_group study,study_method_mixed,study_method_notes,study_method_online videos,study_method_textbook
0,18,7.0,90.0,85.0,92.0,88.0,5.0,0.0,0,0,0,0,0,0,0,0,0,0

In [ ]:
# Make a copy to apply transformations
input_df_processed = input_df_raw.copy()

# Ordinal Encoding
input_df_processed['parent_education_encoded'] = encoder_parent_education.transform(input_df_processed[['parent_education']])
input_df_processed['travel_time_encoded'] = encoder_travel_time.transform(input_df_processed[['travel_time']])

# One-Hot Encoding
# Need to create dummy variables for nominal_cols present in the input_df_processed
input_df_processed = pd.get_dummies(input_df_processed, columns=nominal_cols, drop_first=True)

# Drop original categorical columns and 'student_id', 'overall_score', 'final_grade'
columns_to_drop = ordinal_cols + nominal_cols + ['student_id', 'overall_score', 'final_grade']
input_df_processed = input_df_processed.drop(columns=columns_to_drop, errors='ignore')

# Convert boolean columns to int
boolean_cols_input = input_df_processed.select_dtypes(include='bool').columns
input_df_processed[boolean_cols_input] = input_df_processed[boolean_cols_input].astype(int)

# Align columns with training data - this is critical!
# Use the `production_train_columns` which simulates the columns available in a production environment.
input_df_processed = input_df_processed.reindex(columns=production_train_columns, fill_value=0)

display(input_df_processed)

,age,study_hours,attendance_percentage,math_score,science_score,english_score,parent_education_encoded,travel_time_encoded,gender_male,gender_other,school_type_public,internet_access_yes,extra_activities_yes,study_method_group study,study_method_mixed,study_method_notes,study_method_online videos,study_method_textbook
0,18,7.0,90.0,85.0,92.0,88.0,5.0,0.0,0,0,0,0,0,0,0,0,0,0

Now, scale the preprocessed input data using the same `StandardScaler` that was fitted on the training data.

In [ ]:
input_scaled = scaler.transform(input_df_processed)

print("Scaled Input Data:")
print(input_scaled)

Scaled Input Data:
[[ 0.89411245  1.27432194  1.02924805  1.02200225  1.3497048   1.18064779
   1.44997958 -1.36000654 -0.70244495 -0.72607429 -0.98846651 -2.38234494
  -1.02552568 -0.43481104 -0.45545342 -0.45960887 -0.44032635 -0.45032263]]

Finally, make a prediction using the loaded Random Forest model.

In [ ]:
predicted_grade = model_rf.predict(input_scaled)
print(f"The predicted final grade for the input student is: {predicted_grade[0]}")

The predicted final grade for the input student is: b

In [1]:
import pandas as pd
import joblib
import random
from sklearn.preprocessing import OrdinalEncoder

# --- 1. Define global variables used in preprocessing ---
nominal_cols = ['gender', 'school_type', 'internet_access', 'extra_activities', 'study_method']
ordinal_cols = ['parent_education', 'travel_time']

parent_education_order = ['no formal', 'diploma', 'high school', 'graduate', 'post graduate', 'phd']
travel_time_order = ['<15 min', '15-30 min', '30-60 min', '>60 min']

# Re-instantiate OrdinalEncoders with categories they were trained on.
# In a full production pipeline, these fitted encoders would also be saved/loaded.
encoder_parent_education = OrdinalEncoder(categories=[parent_education_order])
encoder_parent_education.fit(pd.DataFrame({'parent_education': parent_education_order})) # Fit to make transform work

encoder_travel_time = OrdinalEncoder(categories=[travel_time_order])
encoder_travel_time.fit(pd.DataFrame({'travel_time': travel_time_order})) # Fit to make transform work

# --- 2. Load the trained model and scaler ---
try:
    model_rf = joblib.load('best_random_forest_model.joblib')
    scaler = joblib.load('scaler.joblib')
    print("Model and Scaler loaded successfully.")
except FileNotFoundError:
    print("Error: Model or Scaler files not found. Make sure 'best_random_forest_model.joblib' and 'scaler.joblib' are in the current directory.")
    # In a real application, you might raise an exception or exit here.
    exit()

# --- 3. Define production_train_columns ---
# This list represents the exact order and names of features the model expects after preprocessing.
production_train_columns = ['age', 'study_hours', 'attendance_percentage', 'math_score', 'science_score',
                            'english_score', 'parent_education_encoded', 'travel_time_encoded',
                            'gender_male', 'gender_other', 'school_type_public', 'internet_access_yes',
                            'extra_activities_yes', 'study_method_group study', 'study_method_mixed',
                            'study_method_notes', 'study_method_online videos', 'study_method_textbook']

# --- 4. Define the prediction function ---
def predict_student_grade(raw_input_data):
    """
    Preprocesses raw student input data and predicts the final grade.

    Args:
        raw_input_data (dict): A dictionary containing student features,
                                e.g., {'age': 18, 'gender': 'male', ...}
                                Excludes 'overall_score' and 'final_grade'.

    Returns:
        str: The predicted final grade.
    """
    # Create DataFrame from raw input
    input_df_raw = pd.DataFrame([raw_input_data])

    # Generate random student_id internally
    if 'student_id' not in input_df_raw.columns:
        input_df_raw['student_id'] = random.randint(100000, 999999)

    # Make a copy for processing
    input_df_processed = input_df_raw.copy()

    # Ordinal Encoding
    input_df_processed['parent_education_encoded'] = encoder_parent_education.transform(input_df_processed[['parent_education']])
    input_df_processed['travel_time_encoded'] = encoder_travel_time.transform(input_df_processed[['travel_time']])

    # One-Hot Encoding
    input_df_processed = pd.get_dummies(input_df_processed, columns=nominal_cols, drop_first=True)

    # Drop original categorical columns and other irrelevant columns
    columns_to_drop = ordinal_cols + nominal_cols + ['student_id', 'overall_score', 'final_grade']
    input_df_processed = input_df_processed.drop(columns=columns_to_drop, errors='ignore')

    # Convert boolean columns to int
    boolean_cols_input = input_df_processed.select_dtypes(include='bool').columns
    if not boolean_cols_input.empty:
        input_df_processed[boolean_cols_input] = input_df_processed[boolean_cols_input].astype(int)

    # Align columns with production_train_columns
    input_df_processed = input_df_processed.reindex(columns=production_train_columns, fill_value=0)

    # Scale the input data
    input_scaled = scaler.transform(input_df_processed)

    # Make prediction
    predicted_grade = model_rf.predict(input_scaled)

    return predicted_grade[0]

# --- 5. Example Usage ---
# Example input data, similar to what a user might provide via an API or form.
# Note: 'student_id', 'overall_score', 'final_grade' are not needed from the user.
example_user_input = {
    'age': 18,
    'gender': 'male',
    'school_type': 'private',
    'parent_education': 'phd',
    'study_hours': 7.0,
    'attendance_percentage': 90.0,
    'internet_access': 'yes',
    'travel_time': '<15 min',
    'extra_activities': 'yes',
    'study_method': 'notes',
    'math_score': 85.0,
    'science_score': 92.0,
    'english_score': 88.0
}

# Make a prediction using the function
final_prediction = predict_student_grade(example_user_input)
print(f"The predicted final grade for the example input is: {final_prediction}")

Model and Scaler loaded successfully.
The predicted final grade for the example input is: b